# -*- coding: utf-8 -*-
"""Consume_wise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqLIKmTdNPgVQEurSTac-Yhjwu3pFSEB
"""

!pip install -q -U google-generativeai

import google.generativeai as genai

GOOGLE_API_KEY='AIzaSyB7QXjKYyjJbB0COlLE19YsWqyHDgVnM1k'
genai.configure(api_key=GOOGLE_API_KEY)

# List available models.
print('Available models:')
for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
      print(f'- {m.name}')
model = genai.GenerativeModel('gemini-pro')

print('\nReady to chat...')
while True:
  prompt= input("You: ")
  response = model.generate_content(prompt)
  result = ''.join([p.text for p in response.candidates[0].content.parts])
  print("My Mind and Me: ", result)